import turtle

t = turtle.Turtle()
t2 = turtle.Turtle()
t2.hideturtle()
t2.penup()
screen = turtle.Screen()

screen.screensize(200,200,)
screen.bgcolor("blue")
t.penup()
t.goto(0,150)
t.penup()
t.write("Intro", font=("Arial", 24, "bold"), align="center")
t.penup()
t.goto(0,125)
t.write("Yohan Francis Racoma", font=("Arial", 20, "bold"), align= "center")
t.goto(0,100)
t.write("This is the intro page. Press enter on your keyboard to flip to the next page!", font=("Times New Roman", 12), align = "center")
t.goto(0,0)
t.fillcolor("light blue")
t.begin_fill()
t.pendown()
t.circle(30)
t.end_fill()
t.penup()
turtle.addshape("nerd.gif")
turtle.addshape("juventus.gif")
t2.penup()
t2.goto(-200,150)
t2.shape("nerd.gif")
a = t2.stamp()
t2.shape("juventus.gif")
t2.goto(200,150)
b = t2.stamp()
t2.goto(200,150)
enter = input("Press enter to continue")
t.clear()
t2.clear()
t2.clearstamps()

screen.bgcolor("pink")
t.goto(0,0)
t.fillcolor("blue")
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.pendown()
t.end_fill()
t.penup()
t.goto(0,175)
t.write("Favorite Foods", font=("Arial", 24, "bold"), align = "center")
turtle.addshape("filipino food.gif")
turtle.addshape("season 52.gif")
t2.penup()
t.goto(-200,75)
t.write("Season 52", font=("Arial", 20, "bold"), align= "center")
t2.shape("filipino food.gif")
t2.goto(200,150)
c = t2.stamp()
t.goto(200,75)
t.write("Filipino Food", font=("Arial", 20, "bold"), align= "center")
t2.shape("season 52.gif")
t2.goto(0,-100)
d = t2.stamp()
t.goto(0,-175)
t.write("Pomegranate", font=("Arial", 20, "bold"), align= "center")
enter = input("Press enter to continue")
t.clear()
t2.clear()
t2.clearstamps()

screen.bgcolor("orange")
t.goto(0,0)
t.fillcolor("light green")
t.begin_fill()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.pendown()
t.end_fill()
t.penup()
t.goto(0,175)
t.write("Hobbies", font=("Arial", 24, "bold"), align = "center")
turtle.addshape("dancing.gif")
turtle.addshape("youtube.gif")
t2.penup()
t.goto(-200,75)
t.write("Dancing filipino dances", font=("Arial", 20, "bold"), align= "center")
t2.shape("dancing.gif")
t2.goto(200,150)
e = t2.stamp()
t.goto(200,75)
t.write("Watching youtube", font=("Arial", 20, "bold"), align= "center")
t2.shape("youtube.gif")
t2.goto(0,-200)
f = t2.stamp()
t2.goto(0,-100)
t.goto(200,-75)
t.write("Eating", font=("Arial", 20, "bold"), align= "center")
t.goto(-200,-75)
t.write("Hanging Out with Friends", font=("Arial", 20, "bold"), align= "center")
enter = input("Press enter to continue")
t.clear()
t2.clearstamps()
t2.clear()

screen.bgcolor("green")
t.goto(0,0)
t.fillcolor("purple")
t.begin_fill()
t.pendown()
t.forward(150)
t.right(90)
t.forward(100)
t.right(90)
t.forward(150)
t.right(90)
t.forward(100)
t.end_fill()
t.penup()
t.goto(0,175)
t.write("Favorite Movie", font=("Arial", 24, "bold"), align = "center")
# paste picture here
turtle.addshape("spongebob.gif")
turtle.addshape("spongebob M.gif")
t2.penup()
t.goto(-200,75)
t2.shape("spongebob.gif")
t2.goto(200,150)
g = t2.stamp()
t2.goto(200,150)
t.goto(0,50)
t.write("Spongebob The Movie", font=("Arial", 20, "bold"), align= "center")
t2.shape("spongebob M.gif")
t2.goto(0,-200)
h = t2.stamp()
t2.goto(0,-200)
enter = input("Press enter to continue")
t.clear()
t2.clearstamps()

screen.bgcolor("purple")
t.goto(0,0)
t.fillcolor("pink")
t.begin_fill()
t.pendown()
t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.forward(100)
t.end_fill()
t.penup()
t.goto(0,175)
t.write("Favorite Sport", font=("Arial", 24, "bold"), align = "center")
# paste picture here
turtle.addshape("volleyball 1.gif")
turtle.addshape("volleyball 2.gif")
t2.penup()
t.goto(0,-175)
t.write("volleyball", font=("Arial", 20, "bold"), align= "center")
t2.shape("volleyball 1.gif")
t2.goto(200,150)
i = t2.stamp()
t.goto(200,75)
t2.shape("volleyball 2.gif")
t2.goto(0,-100)
j = t2.stamp()
t2.goto(0,-100)
turtle.done()